version: '3.8'

services:
  kartverketprosjekt:
    image: ${DOCKER_REGISTRY-}kartverketprosjekt
    build:
      context: .
      dockerfile: KartverketProsjekt/Dockerfile
    ports:
      - "8080:8080"  # Maps host port 8080 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mariadb;Database=KartverketDb;User=root;Password=kartverket
    depends_on:
      - mariadb


  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kartverket
      MYSQL_DATABASE: KartverketDb
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:
