services:
  kartverketprosjekt:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ./secrets:/home/app/.microsoft/usersecrets:ro   # Relative path for UserSecrets
      - ./https:/home/app/.aspnet/https:ro              # Relative path for HTTPS certificates
